#!/bin/bash
# Generate folders for web development

# Initialize git
# git init
# CLONE from github first

touch .gitignore

# Initialize project, creates package.json, Install gulp and gulp-sass
npm init

# Setup gulp dev environment
npm install gulp --save-dev
npm install gulp-sass --save-dev
npm install gulp-clean-css --save-dev
npm install gulp-imagemin --save-dev
npm install gulp-minify --save-dev
npm install browser-sync --save-dev

touch gulpfile.js

# Create docker files
touch Dockerfile
touch docker-compose.yml


# Create directories app and dist
mkdir src
mkdir dist

cd src

# Create directories in app
mkdir css
mkdir scss
mkdir js
mkdir img

# Create files
touch index.html
