#!/usr/bin/env python3

import calendar
import sys
from datetime import datetime

def get_day_of_the_week(number):
    days = ['M', 'T', 'W', 'T', 'F', 'S', 'S']
    return days[number]

def print_dates(firstDayOfTheMonth, numberOfDays):
    dayOfTheMonth = firstDayOfTheMonth
    for date in range(1, numberOfDays + 1):
        print(str(date) + get_day_of_the_week(dayOfTheMonth % 7))
        dayOfTheMonth += 1

# Main Program

# If month and year are given, the use that to generate monthly log
# else use current month and year
if len(sys.argv) == 3:
    month = int(sys.argv[1])
    year = int(sys.argv[2])
else:
    month = datetime.now().month
    year = datetime.now().year

firstDayOfTheMonth, numberOfDays = calendar.monthrange(year, month)

print_dates(firstDayOfTheMonth, numberOfDays)
